# This is a basic workflow to help you to deploy to gh-branch with Actions

name: CI
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - name: Deploy Pages
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        branch: gh-pages
        folder: build
